/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-container': '#2563eb',
        'tertiary-fixed': '#6ffbbe',
        'surface-tint': '#0053db',
        'secondary-fixed': '#89f5e7',
        'outline-variant': '#c3c6d7',
        'on-primary-fixed': '#00174b',
        'primary-fixed-dim': '#b4c5ff',
        'secondary-container': '#86f2e4',
        'primary-fixed': '#dbe1ff',
        'background': '#f7f9fb',
        'on-error': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'surface-bright': '#f7f9fb',
        'inverse-on-surface': '#eff1f3',
        'tertiary-container': '#007d55',
        'error': '#ba1a1a',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#003ea8',
        'on-primary-container': '#eeefff',
        'tertiary-fixed-dim': '#4edea3',
        'tertiary': '#006242',
        'secondary': '#006a61',
        'surface-container-highest': '#e0e3e5',
        'on-background': '#191c1e',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-container': '#bdffdb',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'primary': '#004ac6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#005236',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed-variant': '#005049',
        'on-secondary-container': '#006f66',
        'outline': '#737686',
        'surface-dim': '#d8dadc',
        'on-secondary-fixed': '#00201d',
        'on-surface-variant': '#434655',
        'surface-container-low': '#f2f4f6',
        'inverse-surface': '#2d3133',
        'surface': '#f7f9fb',
        'surface-container': '#eceef0',
        'on-primary': '#ffffff',
        'on-surface': '#191c1e',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#6bd8cb',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'base': '8px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
