FROM node:22-alpine as base

WORKDIR /app

# Copy package configuration and install dependencies
COPY frontend/package.json frontend/package-lock.json* /app/
RUN npm install

# Copy frontend source code
COPY frontend /app/

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
